var age = 20;
console.log(age);
var age = 30;
console.log(age);
var name = "John";
console.log(name);
var salary = 50000;
console.log(salary);
let age = 25;
console.log(age);
age = 35;
let name = "Alice";
console.log(name);
const pi = 3.14;
console.log(pi);
